from keyboards.kb_client import client_kb
from keyboards.kb_student import student_kb
from keyboards.kb_student_eng_rus import student_eng_rus_kb
from keyboards.kb_student_rus_eng import student_rus_eng_kb